services:
  app:
    build: .
    entrypoint: /home/node/app/.docker/entrypoint.sh
    container_name: sweet-shop-back-app
    ports:
      - '3001:3001' # Expose app port
      - '5555:5555' # Expose prisma studio port
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - db_test
    networks:
      - app-network
  db:
    build: .docker/postgres
    container_name: sweet-shop-back-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=sweet-shop-back-secret
      - POSTGRES_DB=sweet-shop-back
    networks:
      - app-network
  
  db_test:
    image: postgres:16
    container_name: sweet-shop-back-db-test
    restart: always
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=sweet-shop-back-test
    volumes:
      - .docker/dbdata-test:/var/lib/postgresql/data-test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
